### ISSUE TITLE
week7 텍스트감성분류.ipynb 와 README.md

### ISSUE THREAD

**Issue by YujinJI** [SPAI-Lab/GenerativeAI_Study#32]
사소합니다만

### 텍스트감성분류.ipynb
```python
# 결과 출력
if test_output[0][0] > 0.5:
    print('{} - 긍정적인 리뷰({:.3f})'.format(test_sent, test_output[0][0]))
else:
    print('{} - 부정적인 리뷰({:.3f})'.format(test_sent, test_output[0][0]))
``` 

의도대로라면 부정적인 리뷰의 확률이 `1-test_output[0][0]`이 되어야 하지 않을까요?

### README.md
```
target 평점 분류 : 1,2,3,4,5점(총 5개 범주)
```

![image](https://github.com/SPAI-Lab/GenerativeAI_Study/assets/59556524/3e073845-b573-4e50-ad44-469599e28fed)

**Comment by BluePinetree** [comment]
# 텍스트감성분류.ipynb
오 감사합니다. 수정하도록 하겠습니다잉.

# README.md
내이스합니다. 레이블 3이 존재하지 않는다는 정보는 직접 분석을 진행해야만 알 수 있는 정보이므로 ~~해보지 않은 친구들이 계속 속을 수 있게 유지하도록 하겠습니다.~~
